npm:
  build: ./
  volumes:
    - .:/bg-web
  entrypoint: ['/usr/local/bin/npm']

bower:
  build: ./
  volumes:
    - .:/bg-web
  entrypoint: ['/usr/local/bin/bower', '--allow-root']

server:
  build: ./
  volumes:
    - .:/bg-web
  command: server --watcher polling
  ports:
    - "4200:4200"
    - "49152:49152"
